#!/bin/bash

trap 'echo "Error on line $LINENO while running: $BASH_COMMAND" | tee -a ./qemu.log >&2' ERR

HOOKS_DIR=$(dirname "$0")

VM_NAME="$1"    # domain name
EVENT="$2"      # start, stopped, etc.
PHASE="$3"      # begin, end, etc.

LIB_DIR="$HOOKS_DIR/lib"

# Before VM starts -> allocate hugepages
if [ "$EVENT" = "prepare" ] && [ "$PHASE" = "begin" ]; then
    if [ -x "$LIB_DIR/hugepages.sh" ]; then
        "$LIB_DIR/hugepages.sh" "$VM_NAME" "allocate"
    fi
fi

#Before VM starts isolate the cpus
if [ "$EVENT" = "prepare" ] && [ "$PHASE" = "begin" ]; then
    if [ -x "$LIB_DIR/isolatecpus.sh" ]; then
        "$LIB_DIR/isolatecpus.sh" "$VM_NAME" "isolate"
    fi
fi

# After VM stops -> remove hugepages
if [ "$EVENT" = "release" ] && [ "$PHASE" = "end" ]; then
    if [ -x "$LIB_DIR/hugepages.sh" ]; then
        "$LIB_DIR/hugepages.sh" "$VM_NAME" "release"
    fi
fi

# After VM stops de-isolate the cpus
if [ "$EVENT" = "release" ] && [ "$PHASE" = "end" ]; then
    if [ -x "$LIB_DIR/isolatecpus.sh" ]; then
        "$LIB_DIR/isolatecpus.sh" "$VM_NAME" "deisolate"
    fi
fi
